# Generated by Django 5.1 on 2024-11-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopagriai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
