# Generated by Django 5.1 on 2024-11-11 03:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SoilTestRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Request Accepted", "Request Accepted"),
                            ("Denied", "Denied"),
                            ("Sample Collected", "Sample Collected"),
                            ("Arrived at Lab", "Arrived at Lab"),
                            ("Pending", "Pending"),
                            ("Test Completed", "Test Completed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "tracking_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("nitrogen", models.FloatField(blank=True, null=True)),
                ("phosphorus", models.FloatField(blank=True, null=True)),
                ("potassium", models.FloatField(blank=True, null=True)),
                ("pH", models.FloatField(blank=True, null=True)),
                ("copper", models.FloatField(blank=True, null=True)),
                ("boron", models.FloatField(blank=True, null=True)),
                ("sulfur", models.FloatField(blank=True, null=True)),
                ("iron", models.FloatField(blank=True, null=True)),
                ("zinc", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
