# Generated by Django 5.1 on 2024-10-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_profile_uid_alter_profile_otp_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x000002442C4B14E0>", max_length=200
            ),
        ),
    ]
