# Generated by Django 5.1 on 2024-10-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_profile_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x000001F737D514E0>", max_length=200
            ),
        ),
    ]
