# Generated by Django 5.1 on 2024-11-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0031_alter_profile_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(
                default="<function uuid4 at 0x0000027164B4D4E0>", max_length=200
            ),
        ),
    ]
